== Spring GraphQL with Spring Data Neo4j

This example project shows how to combine https://docs.spring.io/spring-graphql/docs/1.0.0-M1/reference/html/[Spring GraphQL] with https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#reference[Spring Data Neo4j].

NOTE: This project needs Spring GraphQL M1 and Spring Data Neo4j 6.2.0-SNAPSHOT (30.07.2021 or later)

=== Try it out


==== Hosted instance

An hosted instance is available at https://spring-graphql-neo4j.herokuapp.com/graphiql?path=/graphql

==== Run the application yourself

For this example we are using Docker.

[source,bash]
----
 docker run -p7474:7474 -p7687:7687 --env NEO4J_AUTH=neo4j/secret neo4j:4.3
----

When your local instance is running please adjust the connections parameters in your _application.properties_ file.

.application.properties
----
spring.neo4j.uri=neo4j://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=secret
----

When you start the application, the example movie data set will get published to the database.

[source,shell]
----
./mvnw spring-boot:run
----

=== What to explore

The current schema looks like this:

[source,graphql endpoint]
.schema.graphqls
----
type Query {
    movies : [Movie]
    movie(title : String!) : Movie
}

type Movie {
    title: String!
    description : String!
    overview: String
    actors: [Person]
    directors: [Person]
}

type Person {
    name: String!
    yearOfBirth: Int
}
----

Example queries as you can see above are:

[source,graphql]
.Query all movies
----
{movies {title, actors {name, yearOfBirth}}}
----
will return:

[source, json]
----
{
  "data": {
    "movies": [
      {
        "title": "The Matrix",
        "actors": [
          {
            "name": "Gloria Foster",
            "yearOfBirth": null
          },
          {
            "name": "Hugo Weaving",
            "yearOfBirth": 1960
          },
          {
            "name": "Keanu Reeves",
            "yearOfBirth": 1964
          },
          {
            "name": "Emil Eifrem",
            "yearOfBirth": 1978
          }, ...
     ]},
     {
        "title": "The Matrix Reloaded",
        "actors": [
          {
            "name": "Gloria Foster",
            "yearOfBirth": null
          }, ....
        ]}
    ]}
}
----

[source,graphql]
.Query one particular movie
----
{movie (title: "The Matrix") {title, description}}
----

will return:

[source, json]
----
{
  "data": {
    "movie": {
      "title": "The Matrix",
      "description": "Welcome to the Real World"
    }
  }
}
----

==== Multiple sources

It is possible to aggregate the data from different sources.
For example the `overview` field of the `Movie` will get fetched from https://www.themoviedb.org/.

Please keep in mind that it would make sense to mark the `overview` field as optional to fetch and wrap the retrieval into a resilience library (e.g. for retries).
Also instead of delivering the value of the field, we could _just_ provide a link for the GraphQL client to get the data itself.
This would avoid that this application gets the bottleneck of communication.