== Spring GraphQL with Spring Data Neo4j

This example project shows how to combine https://docs.spring.io/spring-graphql/docs/1.2.0/reference/html/[Spring GraphQL 1.2.0] with https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#reference[Spring Data Neo4j 7.1.0].
The project itself is based on Spring Boot 3.1 to make use of some very nice improvements.

=== Planned features / tasks for this example

* Support for Scroll/Pagination https://docs.spring.io/spring-graphql/docs/current/reference/html/#data.pagination.scroll
** Need to implement functionality in Spring Data Neo4j first
* Native compilation documentation

=== Features used in this example

==== New Testcontainers support features

* `@ServiceConnection`: https://docs.spring.io/spring-boot/docs/3.1.x/reference/htmlsingle/#features.testing.testcontainers.service-connections
* Testcontainers at development time: https://docs.spring.io/spring-boot/docs/3.1.x/reference/htmlsingle/#features.testing.testcontainers.at-development-time
* `@ImportTestcontainers`: https://docs.spring.io/spring-boot/docs/3.1.x/reference/htmlsingle/#features.testing.testcontainers.at-development-time.importing-container-declarations

==== Neo4j-Migrations for test data creation

Starting the application from the tests or running integration tests, the project will use https://github.com/michael-simons/neo4j-migrations[Neo4j-Migrations] to create the initial dataset.

=== Try it out

==== Run the application yourself

===== With a test database

The project provides a Neo4j testcontainer instance if it gets started from the tests. (Docker needed)

[source,shell]
----
./mvnw spring-boot:test-run
----

===== With a "production" database

If you want to connect to a running instance, you have to start the application with the matching environment variables

[source,shell]
----
SPRING_NEO4J_AUTHENTICATION_PASSWORD=<your password> \\
SPRING_NEO4j_URI=<your uri, default bolt://localhost:7687> \\
./mvnw spring-boot:run
----

Please keep in mind that the application is focused on using the movie dataset.
If not happen yet, please run the `:play movies` guide and the Cypher query to populate the database.

=== What to explore

The current schema looks like this:

[source,graphql endpoint]
.schema.graphqls
----
type Query {
    movies : [Movie]
    movie(title : String!) : Movie
}

type Movie {
    id: ID!
    title: String!
    description : String!
    "Random number 0 - 100 as an example for aggregation of data"
    rating: Int
    actors: [Person]
    directors: [Person]
}

"A person is either an actor or a director"
type Person {
    id: ID!
    name: String!
    yearOfBirth: Int
}
----

Example queries as you can see above are:

[source,graphql]
.Query all movies
----
{movies {title, actors {name, yearOfBirth}}}
----
will return:

[source, json]
----
{
  "data": {
    "movies": [
      {
        "title": "The Matrix",
        "actors": [
          {
            "name": "Gloria Foster",
            "yearOfBirth": null
          },
          {
            "name": "Hugo Weaving",
            "yearOfBirth": 1960
          },
          {
            "name": "Keanu Reeves",
            "yearOfBirth": 1964
          },
          {
            "name": "Emil Eifrem",
            "yearOfBirth": 1978
          }, ...
     ]},
     {
        "title": "The Matrix Reloaded",
        "actors": [
          {
            "name": "Gloria Foster",
            "yearOfBirth": null
          }, ....
        ]}
    ]}
}
----

[source,graphql]
.Query one particular movie
----
{movie (title: "The Matrix") {title, description}}
----

will return:

[source, json]
----
{
  "data": {
    "movie": {
      "title": "The Matrix",
      "description": "Welcome to the Real World"
    }
  }
}
----

==== Multiple sources

It is possible to aggregate the data from different sources.
For example the `rating` field of the `Movie` will be a random generated number between 0 and 100.

[source,graphql]
.Query movie with field from other source
----
{movie (title: "The Matrix") {title, rating}}
----

returns

[source, json]
----
{
  "data": {
    "movie": {
      "title": "The Matrix",
      "rating": 99
    }
  }
}
----
